# FROM node:16-alpine

# WORKDIR '/app'

# COPY package.json .
# RUN npm install

# COPY . .

# CMD ["npm", "run", "start"]

# Use the official Node.js image.
# https://hub.docker.com/_/node

FROM node:16-alpine

# Create and change to the app directory.
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
COPY package*.json ./

# Install dependencies.
RUN npm install

# Copy local code to the container image.
COPY . .

# Expose the port on which your app runs
EXPOSE 80

# Run the web service on container startup.
CMD [ "npm", "start" ]
